fix: add text and bg colors to loading toast
fmaclen/hollama pull request #217
Opened 2024-10-15 12:34 UTC by GregoMac1

2024-10-16 13:01 UTC, fmaclen requested changes
Thanks for tacking this one, just left you some minor notes about the colors used.
Everything else looks good!

2024-10-16 13:01 UTC, fmaclen commented on src/routes/+layout.svelte
> +			loading: 'text-shade-12 bg-shade-4',
BTW, I have an eternal struggle with color tokens and color shades. I've tried many different naming conventions and color progressions and I'm never satisfied, though the setup we have in Hollama is probably one of the best ones I've come up with so far, but it's still not good enough.

I'd be happy to go on a rant about this next time we talk if you are interested 😅

2024-10-18 14:25 UTC, GregoMac1 commented on src/routes/+layout.svelte
> +			loading: 'text-shade-12 bg-shade-4',
You're right, my bad about `text-shade-12`. Regarding `bg-shade-0`, I like how it looks in Light mode but I don't love it in Dark mode. I feel like it should have a lighter color than the container background, not darker (black), but it's just my impression.

Sure! We can absolutely talk about the color scheme. I think it's pretty good anyway! 🙌🏻

2024-10-18 20:54 UTC, fmaclen approved these changes
🚀

2024-10-18 21:00 UTC, fmaclen commented on src/routes/+layout.svelte
> +			loading: 'text-shade-12 bg-shade-4',
Yeah, you are right, 100% black doesn't look great on dark mode but that same shade looks way worse in Light mode 😬 

I've been thinking about refactoring the way we UI is themed but haven't had time to sketch it in Figma.

2024-10-18 22:22 UTC, merged

2024-10-18 22:23 UTC, fmaclen commented
:tada: This PR is included in version 0.18.1 :tada:

The release is available on [GitHub release](https://github.com/fmaclen/hollama/releases/tag/0.18.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: