Add language support for Vietnamese language
fmaclen/hollama pull request #224
Opened 2024-10-25 05:59 UTC by PlayerNguyen

This PR follows the issue #223

2024-10-25 06:01 UTC, PlayerNguyen commented
Here is some screenshot under Vietnamese UI

<img width="1392" alt="image" src="https://github.com/user-attachments/assets/6927964c-687e-41f4-95da-a09333dc19ec">
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/c5e9432b-cf25-4e51-92f8-22443102dc6f">

2024-10-25 17:30 UTC, fmaclen requested changes
Thanks for submitting this PR, I think it mostly looks good 👍 
Just left you a minor comment below that needs fixing.

2024-10-25 17:30 UTC, fmaclen commented on src/i18n/vi/index.ts
> +	// messageOfTheDay: 'Thông điệp trong ngày',
Let's remove the empty line, and uncomment (or remove) line 64.

2024-10-26 01:59 UTC, PlayerNguyen commented
@fmaclen I changed it and we are good to go

2024-10-26 02:13 UTC, fmaclen approved these changes
This is great, thanks @PlayerNguyen! 🚀

2024-10-26 02:13 UTC, merged

2024-10-28 15:15 UTC, fmaclen commented
:tada: This PR is included in version 0.20.0 :tada:

The release is available on [GitHub release](https://github.com/fmaclen/hollama/releases/tag/0.20.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: