Add German language support
fmaclen/hollama pull request #241
Opened 2024-11-20 12:51 UTC by jhoermann

Closes #240

2024-11-25 15:13 UTC, fmaclen requested changes
Thanks again for putting this together.

Now that #234 has been merged there were significant changes to the locales, a handful of keys were removed and several more were added.

Here's the specific list of changes:
https://github.com/fmaclen/hollama/pull/234/files#diff-dfa2062fc0f5cfa7c4ef6179d7480621e7f0ab7a8a0e51fe25df994871186146

2024-11-25 17:10 UTC, jhoermann commented on src/routes/settings/Interface.svelte
> +			{ value: 'de', label: 'Deutsch' },
Changed now.

2024-11-25 17:17 UTC, jhoermann commented on tests/settings.test.ts
> +	});
Moved now - still need to adapt the messages though.

2024-11-26 08:52 UTC, jhoermann commented
Did all the changes - can you please check again @fmaclen?

2024-11-26 15:56 UTC, fmaclen approved these changes
This looks great, thanks @jhoermann!

2024-11-26 16:00 UTC, merged

2024-11-26 16:01 UTC, fmaclen commented
:tada: This PR is included in version 0.23.0 :tada:

The release is available on [GitHub release](https://github.com/fmaclen/hollama/releases/tag/0.23.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: