feat: Add 'delete all knowledge' and its corresponding test
fmaclen/hollama pull request #75
Opened 2024-07-10 18:07 UTC by GregoMac1

2024-07-10 19:31 UTC, fmaclen requested changes
Awesome start! 👍 

I think it'd be good to DRY things a bit now that we have a few consistent patterns. Left you some minor notes.

Also, let's remove the screenshots that were generated in `docs.test.ts`.
It's showing diffs for all them simply because your computer and mine have slightly different antialiasing. ~~I'll add a new issue~~ [here's an issue](https://github.com/fmaclen/hollama/issues/76) for generating the screenshots on demand so we don't get diffs on every PR, sorry about that 😬

2024-07-10 19:31 UTC, fmaclen commented on src/routes/+page.svelte
>  			localStorage.removeItem('hollama-settings');
Couple of things:

- `deleteSessions()`, `deleteKnoledge()` and `deleteSettings()` are identical. Let's DRY them to a single `deleteStorage(item: string)` function. 
- We should probably add a dedicated type for `item`. In `store.ts` we are dynamically generating the `localStorage` keys. Let's add an enum and use that as the type, for example: `deleteStorage(item: StorageKey)`
- These would be the values of the `StorageKey` enum: `HOLLAMA_SETTINGS: 'hollama-settings', HOLLAMA_SESSIONS: 'hollama-sessions'` and so on...

2024-07-10 19:31 UTC, fmaclen commented on tests/knowledge.test.ts
> +		));
Minor thing, import [`MOCK_KNOWLEDGE`](https://github.com/fmaclen/hollama/blob/main/tests/utils.ts#L135-L148) and use that to seed the local storage.

One thing to keep in mind is that `page.evaluate()` runs _"inside the browser"_ so you won't have `MOCK_KNOWLEDGE` available, instead you need to pass it as an argument. Here's [an example](https://github.com/fmaclen/hollama/blob/main/tests/session.test.ts#L159-L183).

2024-07-10 19:31 UTC, fmaclen commented on src/routes/+page.svelte
> +			<Button variant="outline" on:click={deleteKnowledge}>Delete all knowledge</Button>
Button's will end up looking something like this:

```suggestion
<Button variant="outline" on:click={()=> deleteStorage(StorageKey.HOLLAMA_KNOWLEDGE}>Delete all knowledge</Button>
```

2024-07-10 22:48 UTC, GregoMac1 commented
> Awesome start! 👍
> 
> I think it'd be good to DRY things a bit now that we have a few consistent patterns. Left you some minor notes.
> 
> Also, let's remove the screenshots that were generated in `docs.test.ts`. It's showing diffs for all them simply because your computer and mine have slightly different antialiasing. ~I'll add a new issue~ [here's an issue](https://github.com/fmaclen/hollama/issues/76) for generating the screenshots on demand so we don't get diffs on every PR, sorry about that 😬

About the screenshots, you are right but we must also be aware that the Settings page's screenshot has changed because the "Delete all knowledge" button was added.

2024-07-10 22:51 UTC, fmaclen commented
> we must also be aware that the Settings page's screenshot has changed because the "Delete all knowledge" button was added.

Yeah, good point! Leave that one in.

---

Also, I just merged #70 and there is now a conflict with your `src/routes/+page.svelte`.

The **Settings** template is now in [`src/routes/settings/+page.svelte`](https://github.com/fmaclen/hollama/blob/main/src/routes/settings/%2Bpage.svelte), to settle the conflicts pull the latest from `main` and move your changes to that version of the file.

2024-07-11 02:20 UTC, fmaclen commented on src/routes/+page.svelte
> +</script>
Super minor thing, can you undo this change?

2024-07-11 02:20 UTC, fmaclen approved these changes
This looks great, thank you @GregoMac1!

2024-07-11 02:38 UTC, merged

2024-07-13 01:05 UTC, fmaclen commented
:tada: This PR is included in version 0.3.1 :tada:

The release is available on [GitHub release](https://github.com/fmaclen/hollama/releases/tag/0.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: