Allow copying an entire session
fmaclen/hollama pull request #91
Opened 2024-07-14 15:40 UTC by web2ls

2024-07-14 21:46 UTC, fmaclen commented
@web2ls I'm not sure if you are still working on this PR of it's ready for review but regardless this feature will need a test.

We run integration tests using [Playwright](https://playwright.dev/). I think we can just add new assertions to the [existing "Copy" tests](https://github.com/fmaclen/hollama/blob/main/tests/session.test.ts#L215-L245).

After you are done feel free to ping me or "request" my review.

2024-07-16 18:36 UTC, web2ls commented
@fmaclen please check it

2024-07-17 13:25 UTC, fmaclen commented on src/routes/sessions/[id]/+page.svelte
> +				<CopyButton content={sessionContent} title="Copy session" />
I think we can simplify the implementation significantly by doing this:

```suggestion
				<CopyButton content={JSON.stringify(session.messages, null, 2)} />
```

Then we can get rid of the `copySessionContent()` function and the `sessionContent` variable.

The result will retain the structure of the session which is useful if you are pasting this session into new session as context or another LLM entirely:

```json
[
  {
    "role": "user",
    "content": "mic check, 1 2 3"
  },
  {
    "role": "ai",
    "content": "Checking the microphone input, 1...2...3."
  },
  {
    "role": "user",
    "content": "hello hello"
  },
  {
    "role": "ai",
    "content": "Hello! Is there anything I can assist you with today? If you have any questions or need assistance, please feel free to ask."
  }
]
```

2024-07-17 13:28 UTC, fmaclen commented on src/routes/sessions/[id]/CopyButton.svelte
> +	<Button title={title} variant="icon" size="icon" on:click={copyContent}>
Let's keep the default `tile="Copy"` attribute for now.

2024-07-17 13:32 UTC, fmaclen commented on tests/session.test.ts
> +		await expect(page.getByTitle('Copy session')).toHaveCount(0);
After removing the custom `title` attribute you can target the "Copy session" button with:

```typescript
await expect(page.locator(".header").getByTitle('Copy')).toHaveCount(0);
```

2024-07-17 13:37 UTC, fmaclen requested changes
Thanks for putting together this PR.
It's a great start 👍 

Left you some notes on a few ways we can simplify the implementation.

2024-07-18 15:33 UTC, fmaclen commented on tests/session.test.ts
> +		await expect(page.getByTitle('Copy session')).toHaveCount(0);
Also, minor formatting issue, can you add an empty line after this assertion?
I'd like to group interactions + assertions in "blocks" separated by empty lines.

2024-07-19 02:49 UTC, fmaclen commented
I just merged #90 and there are 2 minor conflicts in your branch.
Let me know if you need help settling them.

Also, this PR is almost done and I would like to merge it soon if you can, if you can't that's ok, just give me a heads up.

2024-07-20 12:05 UTC, web2ls commented
@fmaclen 
sorry for delay
I've made changes based on your comments.

2024-07-20 13:39 UTC, fmaclen approved these changes
@web2ls this looks great, thank you!

2024-07-20 13:39 UTC, merged

2024-07-20 13:39 UTC, fmaclen commented
:tada: This PR is included in version 0.4.0 :tada:

The release is available on [GitHub release](https://github.com/fmaclen/hollama/releases/tag/0.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: